### ISSUE TITLE
Licensing?

### ISSUE THREAD

**Issue by cmoesel** [Sahero/React-table-v7-example#1]
Thanks for providing this example. I originally found your migration code for ReactTable over at: https://levelup.gitconnected.com/migrating-react-table-from-v6-to-v7-dc840eb7ad7

I'm interested in potentially re-using your `ReactTable` component for upgrading from v6 to v7, but I cannot find information regarding how it is licensed. I assume it is free to use, but would appreciate confirmation of the intended license for this code.

Thanks!

**Comment by Sahero** [comment]
It is free to use. You can give me some credit if you like. 👍

**Comment by cmoesel** [comment]
Thanks, @Sahero.  If I use it, I will definitely give you credit.  Right now I'm just weighing my options to determine if it's worth the trouble.  Ideally I'd go all the way up to v8, but there is no v7 to v8 migration guide available, so... we'll see!  Thanks again.  If I decide to jump to v7, your article and code will be very helpful!
